version: "3.8"

services:
  db:
    image: postgres:15
    container_name: address_pg
    restart: always
    environment:
      POSTGRES_DB: addressdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: address_app
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - PGPASSWORD=postgres

volumes:
  pgdata:
